basic_app/urls.py
from django.urls import path, re_path
from basic_app import views 

#template tagging
app_name = 'basic_app'
urlpatterns = [
    # re_path(r'^$', views.index, name='index'),
    path('relative-url-template', views.index, name='relative-template'),
    path('other-page-template', views.otherpage, name='other-page-name'),
    # path('home/', home.index, name='home'),
]

cbv_app/urls.py
from django.urls import path
from . import views

app_name = 'cbv_app_name'
urlpatterns = [
    # modular routes for applicatin based
    # path('school-list/',views.Index.as_view(), name="school-list"),
    path('school-list/',views.SchoolList.as_view(), name="school-list"),
    path('school-detail/<int:pk>/',views.SchoolDetail.as_view(), name="school-details-page"),
    path('school-create/',views.CreateSchool.as_view(), name="school-create"),
    path('school-update/<int:pk>/',views.UpdateSchool.as_view(), name="school-update"),
    path('school-delete/<int:pk>/',views.DeleteSchool.as_view(), name="school-delete"),

]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('', views.index, name='index'),
    # modular routes for applicatin based
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('contact-us/',views.contactUs, name='contact-page'),
    path('sign-up/',views.sign_up, name='signup-page'),
    path('basic-app/',include('basic_app.urls')),
    path('cbv-app/',include('cbv_app.urls'))
]

basic_app/models.py
from django.db import models

# Create your models here.

basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import views

# Create your views here.
def index(request):
    return render(request, 'basic_app/relative_template.html' )

def otherpage(request):
    return render(request, 'basic_app/other.html' )
    

templates/basic_app/other.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Other Template Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class ="col-md-6 text-center">
            <h2>Other Template Page</h2>
           
        </div>
        <div class ="col-md-6">

        </div>

    </div>
</body>
</html>

templates/basic_app/relative_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Relative Template Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class ="col-md-6 text-center">
            <h2>Relative Template Page</h2>
            <a href = "{% url 'basic_app:other-page-name' %}">Other Page</a>
            <a href = "{% url 'admin:index' %}">Admin</a>
            <a href = "{% url 'index' %}">Main Url</a>
        </div>
        <div class ="col-md-6">

        </div>

    </div>
</body>
</html>