cbv_app/urls.py
from django.urls import path
from . import views

app_name = 'cbv_app_name'
urlpatterns = [
    # modular routes for applicatin based
    # path('school-list/',views.Index.as_view(), name="school-list"),
    path('school-list/',views.SchoolList.as_view(), name="school-list"),
    path('school-detail/<int:pk>/',views.SchoolDetail.as_view(), name="school-details-page"),
    path('school-create/',views.CreateSchool.as_view(), name="school-create"),
    path('school-update/<int:pk>/',views.UpdateSchool.as_view(), name="school-update"),
    path('school-delete/<int:pk>/',views.DeleteSchool.as_view(), name="school-delete"),

]

first_app/urls.py
from django.urls import path, re_path
from first_app import views 
from first_app.custom_views import home,class_base_views

#template tagging
app_name = 'first_app'
urlpatterns = [
    # re_path(r'^$', views.index, name='index'),
    path('', views.index, name='index'),
    path('home/', home.index, name='home'),
    path('signup-auth/', views.signup_auth, name='registration'),
    path('login-auth/', views.login_auth, name='login'),
    path('logout/', views.logout_call, name='logout'),
    path('cbv/',class_base_views.ClassBasedView.as_view())

]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('', views.index, name='index'),
    # modular routes for applicatin based
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('contact-us/',views.contactUs, name='contact-page'),
    path('sign-up/',views.sign_up, name='signup-page'),
    path('basic-app/',include('basic_app.urls')),
    path('cbv-app/',include('cbv_app.urls'))
]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User as MainUser

# Create your models here.
class Student(models.Model):
    id = models.IntegerField(primary_key=True,unique=True)
    first_name = models.TextField(max_length=50)
    last_name = models.TextField(max_length=50)
    email =  models.TextField(max_length=50,unique=True)
    # Returns the last entry
    def __str__(self):
        return self.first_name

class Books(models.Model):
    book_id = models.IntegerField(primary_key=True,unique=True)
    book_name = models.TextField(max_length=50)

    def __str__(self):
        return self.book_name

class StudentBooks(models.Model):
    rel_id      = models.IntegerField(primary_key=True)
    book_id     = models.ForeignKey(Books, on_delete=models.CASCADE,)
    student_id  = models.ForeignKey(Student, on_delete=models.CASCADE,)

class User(models.Model):
    firstname   = models.CharField(max_length=200)
    lastname    = models.CharField(max_length=200)
    email       = models.CharField(max_length=200)

class UserProfileMoreInformationForm(models.Model):

    # relation of this form with existing signup page
    user = models.OneToOneField(MainUser, on_delete=models.CASCADE,)

    # Additional info
    web_url = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='first_app/profile_pics',blank=True)

first_app/forms.py
from typing import Any, Dict
from django import forms
from django.core import validators

# For custom validations using validators

def check_name_having_text(value):
    if 'shubham' not in value:
        raise validators.ValidationError('First name should contains word shubham')


class ContanctForm(forms.Form):
    STATUS_CHOICES = (
        (1,("Male")),
        (2,("FeMale")),
        (3,("Other")),
    )
    # name    = forms.CharField(required=True, validators=[validators.MaxLengthValidator(10)])
    #custom validation likes
    name    = forms.CharField(required=True, validators=[check_name_having_text])
    email   = forms.EmailField(label='Enter your email')
    reemail = forms.EmailField(label='Enter your email again')
    gender  = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.RadioSelect,initial="1")
    message = forms.CharField(widget=forms.Textarea)

    # Another method of validation
    def clean(self):
        all_details = super().clean()
        email = all_details['email']
        reemail = all_details['reemail']

        if email !=  reemail:
            raise forms.ValidationError('Both tha entered emails are not matching')

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Student, StudentBooks, Books
from first_app import forms, signup, signup_auth_form
# for login
from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# Create your views here.
def index(request):
    user_details = {'name':'shubham', 'last_name':'kaushalya'}
    student_details = Student.objects.order_by('id')
    student_data = {'student_record':student_details}
    # print(student_data)
    # return render(request, 'first_app/index.html', context=student_data)
    return render(request, 'first_app/index.html',{'name':'shubham', 'last_name':'kaushalya' ,'student_record':student_details})
    # return HttpResponse('stat')
    # return HttpResponse('Welcome shubham in django application')

def contactUs(request):
    form = forms.ContanctForm()

    if request.method == 'POST':
        # print('sfsd')
        form = forms.ContanctForm(request.POST)
        if form.is_valid():
            print('Data validation success')
            print('Name is: '+form.cleaned_data['name'])
            print('email is: '+form.cleaned_data['email'])
            print('gender is: '+form.cleaned_data['gender'])
            print('message is: '+form.cleaned_data['message'])

    return render(request, 'first_app/contact_form.html',{'form':form})

# Signup form using Modal type form 
def sign_up(request):
    signupform = signup.Signup()
    if request.method == 'POST':
        form = signup.Signup(request.POST)
        if  form.is_valid():
            form.save()
            return index(request)

    return render(request, 'first_app/signup.html',{"form":signupform})

def signup_auth(request):

    registered = False

    if request.method == 'POST':

        user_form = signup_auth_form.UserForm(data=request.POST)
        profile_form = signup_auth_form.UserProfileMoreInformationFormView(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            save_user = user_form.save()

            save_user.set_password(save_user.password)

            save_user.save()

            profile = profile_form.save(commit=False)

            profile.user =  save_user

            if 'profile_pic' in request.FILES:

                print('profile available')

                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

            print('ok')
        else: 
             print('fail')
             print(user_form.errors,profile_form.errors)

    else:

        user_form = signup_auth_form.UserForm()
        profile_form = signup_auth_form.UserProfileMoreInformationFormView()

    return render(request, 'first_app/signup_auth.html',{"user_form":user_form,"profile_form":profile_form,'registered':registered })


def login_auth(request):

    # return HttpResponseRedirect('/first_app/home')
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_obj = authenticate(username=username, password=password)
        if user_obj:
             if user_obj.is_active:
                    test = login(request,user_obj)
                    # print('test---------------')
                    print(request.user.get_full_name())
                    return HttpResponseRedirect('/first_app/home')
                    # return HttpResponseRedirect(reverse('contact-page'))
             else:
                 return HttpResponse('You account is not activated yet')

        else:
            return HttpResponse('Something went wrong')
        
    else:
        return render(request, 'first_app/login.html',{})
    
def logout_call(request):
    logout(request)
    return HttpResponseRedirect('/first_app/home')

templates/first_app/cbv.html
<!DOCTYPE html>
{% extends "first_app/header.html" %}
{% block body_block %}
<h1> Welcome in Class Based View</h1>
<h3>{{ my_current_topic }}</h3>
{% endblock %}

templates/first_app/contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Contact Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class ="col-md-6 text-center">
            <h2>Contact Us</h2>
            <form method="post" action="">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="submit">
            </form>
        </div>
        <div class ="col-md-6">

        </div>

    </div>
</body>
</html>

templates/first_app/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Header Section</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'first_app:home' %}">Brand Logo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
            <li class="nav-item">
                  <a class="nav-link" href="{% url 'contact-page' %}">Contact Us</a>
                </li> 
                <!-- <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </li> -->
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Welcome {{ user.get_full_name }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'first_app:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'first_app:registration' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'first_app:login' %}">Login</a>
                </li>
                {% endif %}
                <!-- <li class="nav-item">
                  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li> -->
              </ul>
              <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form> -->
            </div>
          </nav>
    </div>
    <div class="container">
        {% block body_block %}
            <!-- Anything outside of will be import if we inherited -->
            {% endblock %}
    </div>
    {% include 'first_app/footer.html' %}

templates/first_app/home.html
<!DOCTYPE html>
{% extends "first_app/header.html" %}
{% block body_block %}
{% load custom_filters %}
<div class="row">
    <h3 class="col-sm-12">Template Filters Examples:</h3>
    <h4 class="col-sm-12" >{{ name|upper }}</h4>
    <h4 class="col-sm-12">{{ number|add:"1000" }}</h4>
    <h4 class="col-sm-12" >{{ name|callme:"test" }}</h4>
</div>
<dl class="row">
   
    <p>=================================================================================================================</p><br />
    <dt class="col-sm-3">Description lists</dt>
    <dd class="col-sm-9">A description list is perfect for defining terms.</dd>
  
    <dt class="col-sm-3">Euismod</dt>
    <dd class="col-sm-9">
      <p>Vestibulum id ligula porta felis euismod semper eget lacinia odio sem nec elit.</p>
      <p>Donec id elit non mi porta gravida at eget metus.</p>
    </dd>
  
    <dt class="col-sm-3">Malesuada porta</dt>
    <dd class="col-sm-9">Etiam porta sem malesuada magna mollis euismod.</dd>
  
    <dt class="col-sm-3 text-truncate">Truncated term is truncated</dt>
    <dd class="col-sm-9">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</dd>
  
    <dt class="col-sm-3">Nesting</dt>
    <dd class="col-sm-9">
      <dl class="row">
        <dt class="col-sm-4">Nested definition list</dt>
        <dd class="col-sm-8">Aenean posuere, tortor sed cursus feugiat, nunc augue blandit nunc.</dd>
      </dl>
    </dd>
  </dl>
  {% endblock %}

templates/first_app/index.html
<!DOCTYPE html>
{%  load static  %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/style.css'' %}">
    </head>
    <h1> Hello User, Welcome {{name}} {{last_name}}</h1>
    <img src="{% static 'images/guitar.jpeg' %}" alt="No image available">
    <div class="">
        {% if student_record %}
        <table>
            <thead>
                <th>Id</th>
                <th>Student Name</th>
                <th>Studnet Email</th>
            </thead>
            <tbody>
                {% for data in student_record %}
                   <tr>
                        <td>{{ data.id }}</td>
                        <td>{{ data.first_name }} {{ data.last_name }}</td>
                        <td>{{ data.email }}</td>
                    </tr>
                {% endfor %}
           </tbody>
        </table>
        {% else %}
        <p>No record found</p>
        {% endif %}

    </div>
</html>

templates/first_app/login.html
{% extends "first_app/header.html" %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'first_app:login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
            <br>
          <label for="password">Password</label>
          <input type="password" name="password"  placeholder="Password"><br>

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

templates/first_app/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Signup Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class ="col-md-6 text-center">
            <h2>Signup up page</h2>
            <form method="post" action="">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="submit">
            </form>
        </div>
        <div class ="col-md-6">

        </div>

    </div>
</body>
</html>

templates/first_app/signup_auth.html
{% extends "first_app/header.html" %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        {% if registered %}
        <h1>Thank you for register yourself</h1>
        {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
    {% endif %}
    </div>
{% endblock %}