cbv_app/urls.py
from django.urls import path
from . import views

app_name = 'cbv_app_name'
urlpatterns = [
    # modular routes for applicatin based
    # path('school-list/',views.Index.as_view(), name="school-list"),
    path('school-list/',views.SchoolList.as_view(), name="school-list"),
    path('school-detail/<int:pk>/',views.SchoolDetail.as_view(), name="school-details-page"),
    path('school-create/',views.CreateSchool.as_view(), name="school-create"),
    path('school-update/<int:pk>/',views.UpdateSchool.as_view(), name="school-update"),
    path('school-delete/<int:pk>/',views.DeleteSchool.as_view(), name="school-delete"),

]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('', views.index, name='index'),
    # modular routes for applicatin based
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('contact-us/',views.contactUs, name='contact-page'),
    path('sign-up/',views.sign_up, name='signup-page'),
    path('basic-app/',include('basic_app.urls')),
    path('cbv-app/',include('cbv_app.urls'))
]

cbv_app/models.py
from django.db import models

class School(models.Model):
    name        = models.CharField(max_length=256)
    principal   = models.CharField(max_length=256)
    location    = models.CharField(max_length=256)

    def __str__(self) -> str:
        return self.name

class Student(models.Model):
    name    = models.CharField(max_length=256)
    age     = models.PositiveIntegerField()
    school  = models.ForeignKey(School,related_name='students_item', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name

# Create your models here.

cbv_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse

# Create your views here.

class Index(TemplateView):
    model = models.School
    # template_name = 'cbv_app/school_list.html'

class SchoolList(ListView):
     context_object_name = 'school_details'
     model = models.School

class SchoolDetail(DetailView):
     context_object_name = 'school_detail_view'
     model = models.School
     template_name = 'cbv_app/school_detail.html'

class CreateSchool(CreateView):
     model = models.School
     fields = ('name','principal','location')
     template_name = 'cbv_app/create.html'

     def get_success_url(self):
          return reverse('cbv_app_name:school-list')

class UpdateSchool(UpdateView):
     model = models.School
     fields = ('name','principal')
     template_name = 'cbv_app/create.html'
     def get_success_url(self):
          return reverse('cbv_app_name:school-list')
     
class DeleteSchool(DeleteView):
     model = models.School
     def get_success_url(self):
          return reverse('cbv_app_name:school-list')

          
     

cbv_app/templates/cbv_app/create.html
{% extends 'cbv_app/header.html' %}
{% block body_block %}
<h2>School Creation Page</h2>
<form method="post" action="">
    {%csrf_token%}
    {{form.as_p}}
    <input class="bt btn-primary" type="Submit" value="Submit">
</form>
{% endblock %}

cbv_app/templates/cbv_app/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Header Section</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'cbv_app_name:school-list' %}">Brand Logo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cbv_app_name:school-create' %}">Create School</a>
                  </li> 
              </ul>
              <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form> -->
            </div>
          </nav>
    </div>
    <div class="container">
        {% block body_block %}
            <!-- Anything outside of will be import if we inherited -->
        {% endblock %}
    </div>

    <div class="container">
        {% block student_block %}
            <!-- Anything outside of will be import if we inherited -->
        {% endblock %}
    </div>

cbv_app/templates/cbv_app/school_confirm_delete.html
{% extends 'cbv_app/header.html' %}
{% block body_block %}
<form method="post" action="">
    {%csrf_token%}
    {{form.as_p}}
    <h3>Really you want to delete school ?</h3>
    <input class="bt btn-primary" type="Submit" value="Confirm">
</form>
{% endblock %}

cbv_app/templates/cbv_app/school_detail.html
{% extends 'cbv_app/header.html' %}
{% block body_block %}
<h1>School Details Page</h1>
{% if school_detail_view %}
<ol>
    <li><h3>{{school_detail_view.name}}</h3></li>
    <li><h3>{{school_detail_view.location}}</h3></li>
    <li><h3>{{school_detail_view.principal}}</h3></li>
{% endif %}
</ol>
{% endblock %}

{% block student_block %}
<h3>student list</h3>
<ul>
   {% for all_student in school_detail_view.students_item.all %}
        <li><b>{{all_student.name}}</b></li>
   {% endfor %}
</ul>


<h1>Update School</h1>
<div class="container">
    <p><a class='btn btn-warning' href="{% url 'cbv_app_name:school-update' pk=school_detail_view.id %}">Update</a></p>
    <p><a class='btn btn-danger' href="{% url 'cbv_app_name:school-delete' pk=school_detail_view.id %}">Delete</a></p>
</div>


{% endblock %}

cbv_app/templates/cbv_app/school_list.html
{% extends 'cbv_app/header.html' %}
{% block body_block %}
<h1>List of Schools</h1>
{% if school_details %}
<ul>
{% for details in school_details %}
    <li><h3><a href="{% url 'cbv_app_name:school-details-page' details.id %}">{{details.name}}</a></h3></li>
{% endfor %}
{% endif %}
</ul>
{% endblock %}